import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useAuth } from "../../context/AuthContext";
import { LoginModal } from "../Login/LoginModal";
import { ManualTab } from "./ManualTab";
import { ImportJsonTab } from "./ImportJsonTab";
import "./EditorPage.css";

/**
 * EditorPage — quiz creation hub at /editor.
 *
 * Requires authentication. If the user is not signed in, a LoginModal
 * opens automatically (same pattern as GameScreen).
 *
 * Provides two tabs:
 *   - Manual:      fill in quizTitle, category, questions by hand
 *   - Import JSON: paste JSON generated by external AI (ChatGPT / Claude / Gemini)
 *
 * The actual tab content lives in separate components to keep this file thin:
 *   - <ManualTab />     — form-based creation
 *   - <ImportJsonTab /> — paste + validate + upload JSON
 *
 * @component
 * @returns {JSX.Element}
 */
export default function EditorPage() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const navigate = useNavigate();

  // ── Auth gate ─────────────────────────────────────────────────────
  const [loginOpen, setLoginOpen] = useState(true);

  useEffect(() => {
    if (!user) setLoginOpen(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  const handleLoginClose = ({ success } = {}) => {
    setLoginOpen(false);
    if (!success) {
      // User cancelled login → back home
      navigate("/");
    }
  };

  // ── Tab state ─────────────────────────────────────────────────────
  const [activeTab, setActiveTab] = useState("import"); // "manual" | "import"

  // ── Auth gate render ──────────────────────────────────────────────
  if (!user) {
    return (
      <div className="editor-page text-center">
        <h1 className="editor-title">{t("editor.title", "Quiz Lab")}</h1>
        <LoginModal isOpen={loginOpen} onClose={handleLoginClose} />
      </div>
    );
  }

  // ── Main render ───────────────────────────────────────────────────
  return (
    <div className="editor-page">
      <header className="editor-header">
        <h1 className="editor-title">🛠️ {t("editor.title", "Quiz Lab")}</h1>
        <p className="editor-subtitle">
          {t(
            "editor.subtitle",
            "Create a quiz manually or import ready-made JSON from AI",
          )}
        </p>
      </header>

      {/* ── Tabs ────────────────────────────────────────────────── */}
      <nav className="editor-tabs" role="tablist">
        <button
          type="button"
          role="tab"
          aria-selected={activeTab === "import"}
          className={`editor-tab ${activeTab === "import" ? "active" : ""}`}
          onClick={() => setActiveTab("import")}
        >
          📥 {t("editor.tabs.import", "Import JSON")}
        </button>

        <button
          type="button"
          role="tab"
          aria-selected={activeTab === "manual"}
          className={`editor-tab ${activeTab === "manual" ? "active" : ""}`}
          onClick={() => setActiveTab("manual")}
        >
          📝 {t("editor.tabs.manual", "Manual")}
        </button>
      </nav>

      {/* ── Tab content ─────────────────────────────────────────── */}
      <section className="editor-tab-content">
        {activeTab === "manual" && <ManualTab />}
        {activeTab === "import" && <ImportJsonTab />}
      </section>
    </div>
  );
}
